#!/bin/sh
set -e

cat > /app/.env <<EOF
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_ALLOWED_USER_ID=${TELEGRAM_ALLOWED_USER_ID}
OPENCODE_API_URL=${OPENCODE_API_URL:-http://localhost:4096}
OPENCODE_SERVER_USERNAME=${OPENCODE_SERVER_USERNAME:-opencode}
OPENCODE_SERVER_PASSWORD=${OPENCODE_SERVER_PASSWORD}
OPENCODE_MODEL_PROVIDER=${OPENCODE_MODEL_PROVIDER:-opencode}
OPENCODE_MODEL_ID=${OPENCODE_MODEL_ID:-big-pickle}
EOF

exec "$@"
